version: '3'

services:
  web:
    image: kovaro-uaa
    container_name: uaa-server
    # volumes:
      # - ./env/uaa-sample.yml:/env/uaa.yml
    ports:
      - 8080:8080
  db:
    image: postgres:alpine
    container_name: uaa-db
    environment:
      - POSTGRES_PASSWORD=uaa
      - POSTGRES_USER=uaa
      - POSTGRES_DB=uaa
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
