---
# defaults file for roles/uaa
uaa_hostname: "https://uaa.domain.tld"
uaa_admin_client_secret: "assimbonanga"
uaa_db_name: "uaa"
uaa_db_user: "uaa"
uaa_db_password: "uaa"
uaa_db_hostname: "my.db.tld"
uaa_encryption_key: "kovaro-sig"
uaa_encryption_passphrase: "mypassphrase"
uaa_saml_key_label: "kovaro-saml"
uaa_saml_key_filename: "/path/to/server.key"
uaa_saml_passphrase: "key_passphrase_if_required"
uaa_saml_certificate_filename: "/path/to/certificate.crt"
uaa_jwt_key_label: "kovaro_jwt"
uaa_jwt_key: "supersecretJWTsigningKey!$#&!@$#%&PardonMyFrench"
uaa_image_tag: 0.1
