server.port: 3001
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientId: spring
      clientSecret: spring
    resource:
      userInfoUri: http://localhost:8080/userinfo